import fs from "node:fs/promises";
import path from "node:path";
import { actionCatalog, actionHierarchy, actionStates, brandPrinciples, colorGroups, elementCatalog, doDont, motionRules, safeAreas, shapes, socialScaleFormats, socialScaleVars, surfaceRules, tracking, typeFamilies, uiTypeScale, useCases, type GuideToken } from "@/domain/brand-guide";
import { formats } from "@/domain/project";
import { parseRuleVars, parseTokenCss, resolveToken, type TokenMap } from "@/design-system/tokens/parse-css";
import { templates } from "@/features/templates/registry";

/**
 * Renders the design guide in `src/domain/brand-guide.ts` to Markdown, with every
 * value resolved from the live stylesheets. The design-system skill references and
 * the brand kit's guide download are both made here.
 */

export const tokensCssPath = path.join(process.cwd(), "src/design-system/styles/tokens.css");
export const compositionCssPath = path.join(process.cwd(), "src/features/compositions/composition.css");

export type DesignSources = { tokens: TokenMap; social: Record<string, TokenMap> };

export async function loadDesignSources(): Promise<DesignSources> {
  const [tokenCss, compositionCss] = await Promise.all([fs.readFile(tokensCssPath, "utf8"), fs.readFile(compositionCssPath, "utf8")]);
  return { tokens: parseTokenCss(tokenCss), social: socialScale(compositionCss) };
}

/** Each ratio's social type scale: the `.composition` base with its `.format-*` overrides. */
export function socialScale(compositionCss: string): Record<string, TokenMap> {
  const base = parseRuleVars(compositionCss, ".composition");
  return Object.fromEntries(socialScaleFormats.map(({ format, className }) => [format, { ...base, ...parseRuleVars(compositionCss, `.${className}`) }]));
}

const generated = "<!-- Generated by `npm run design:sync` from src/domain/brand-guide.ts and the stylesheets. Do not edit by hand. -->";
const cell = (text: string) => text.replace(/\|/g, "\\|");
const code = (text: string) => `\`${text}\``;
const table = (head: string[], rows: string[][]) => [`| ${head.join(" | ")} |`, `| ${head.map(() => "---").join(" | ")} |`, ...rows.map(row => `| ${row.map(cell).join(" | ")} |`)].join("\n");
const list = (items: readonly string[]) => items.map(item => `- ${item}`).join("\n");
const px = (rem: string | undefined) => rem?.endsWith("rem") ? ` (${parseFloat(rem) * 16}px)` : "";

function tokenRows(tokens: TokenMap, entries: GuideToken[]) {
  return entries.map(entry => [code(entry.token), entry.name, code(resolveToken(tokens, entry.token) ?? "missing"), entry.role]);
}

function prefixed(tokens: TokenMap, prefix: string) {
  return Object.keys(tokens).filter(name => name.startsWith(prefix)).map(name => [code(name), code(resolveToken(tokens, name)!)]);
}

export function renderTokensMarkdown({ tokens, social }: DesignSources): string {
  return [
    "# StatOz design tokens", generated,
    "Values are resolved from `src/design-system/styles/tokens.css` and `src/features/compositions/composition.css`. In code, always use the token name (`var(--ds-…)`), never the value.",
    "## Principles", brandPrinciples.map(p => `- **${p.name}.** ${p.rule}`).join("\n"),
    "## Color",
    ...colorGroups.flatMap(group => [`### ${group.name}`, group.description, table(["Token", "Name", "Value", "Role"], tokenRows(tokens, group.tokens))]),
    "### Overlays", table(["Token", "Value"], prefixed(tokens, "--ds-color-overlay-")),
    "### Gradients", table(["Token", "Value"], prefixed(tokens, "--ds-gradient-")),
    "## Typography", table(["Token", "Family", "Value", "Use"], tokenRows(tokens, typeFamilies)),
    "### UI type ramp", "For studio and product UI. Artwork uses the social scale below.",
    table(["Token", "Name", "Value", "Use"], uiTypeScale.map(entry => [code(entry.token), entry.name, code(`${tokens[entry.token]}${px(tokens[entry.token])}`), entry.role])),
    "### Tracking and leading", table(["Token", "Name", "Value", "Use"], tokenRows(tokens, tracking)), table(["Token", "Value"], prefixed(tokens, "--ds-leading-")),
    `Numbers that change use tabular figures: ${code("font-variant-numeric: tabular-nums")} (token ${code("--ds-numeric-tabular")}).`,
    "### Social artwork scale", "Pixel values on the export canvas, set on `.composition` and overridden per ratio by `.format-*`. Use the variables, not the numbers.",
    table(["Format", "Canvas", ...socialScaleVars.map(code)], socialScaleFormats.map(({ format }) => [`${formats[format].label} (${formats[format].ratio})`, `${formats[format].width}×${formats[format].height}`, ...socialScaleVars.map(name => social[format][name] ?? "–")])),
    "## Shape and surface", table(["Shape", "Clip-path token", "Cut", "Use"], shapes.map(shape => [shape.name, code(shape.clip), shape.cut ? `${code(shape.cut)} = ${tokens[shape.cut]}` : "–", shape.use])),
    list(surfaceRules),
    "### Shadows", table(["Token", "Value"], prefixed(tokens, "--ds-shadow-")),
    "### Spacing", `A 2px rhythm: ${prefixed(tokens, "--ds-space-").map(([name, value]) => `${name} ${value}`).join(", ")}.`,
    "## Layout and motion",
    table(["Format", "Canvas", "Safe area", "Note"], safeAreas.map(area => [`${formats[area.format].label} (${formats[area.format].ratio})`, `${formats[area.format].width}×${formats[area.format].height}`, area.inset, area.note])),
    "Safe areas are house guides, not official platform compliance guarantees.",
    list(motionRules),
  ].join("\n\n") + "\n";
}

function catalogSection(entries: typeof actionCatalog) {
  return entries.flatMap(entry => [`### ${entry.name} · ${code(entry.component)}`, `${entry.use} *Ported from ${entry.from}.*`, list(entry.rules)]);
}

export function renderActionsMarkdown(): string {
  return [
    "# StatOz actions and elements", generated,
    "Import actions from `src/design-system/components/actions.tsx` and elements from `src/design-system/components/elements.tsx`; their styles load globally from `actions.css` and `elements.css`. Every component takes an optional `accent` (any CSS color, usually `var(--ds-color-accent-*)`). The studio shows each one live under Assets & brand → Brand → Actions and Components.",
    "## Which action", list(actionHierarchy),
    "## States every action shows", table(["State", "Treatment"], actionStates.map(item => [item.state, item.rule])),
    "## Actions", ...catalogSection(actionCatalog),
    "## Elements", ...catalogSection(elementCatalog),
  ].join("\n\n") + "\n";
}

export function renderUseCasesMarkdown(): string {
  const names = new Map(templates.map(template => [template.id, template.name]));
  return [
    "# StatOz use-case recipes", generated,
    "Pick the recipe that matches the job, start from the listed studio template, and finish with its checklist. Token names resolve in `tokens.md`.",
    ...useCases.flatMap(useCase => [
      `## ${useCase.name}`, useCase.summary,
      useCase.formats.length ? `**Formats:** ${useCase.formats.map(id => `${formats[id].label} ${formats[id].width}×${formats[id].height}`).join(" · ")}` : "**Formats:** not a studio export.",
      useCase.startTemplates.length ? `**Start from:** ${useCase.startTemplates.map(id => `${names.get(id)} (${code(id)})`).join(", ")}` : "**Start from:** the design-system components and tokens.",
      "**Palette**", list(useCase.palette), "**Type**", list(useCase.type), "**Assets**", list(useCase.assets), "**Rules**", list(useCase.rules),
      "**Checklist**", useCase.checklist.map(item => `- [ ] ${item}`).join("\n"),
    ]),
    "## Do and don't", table(["Topic", "Do", "Don't"], doDont.map(item => [item.topic, item.do, item.dont])),
  ].join("\n\n") + "\n";
}

/** The skill lives with the Codex skills; Claude Code reads its mirror under .claude. */
export const designSkillDir = path.join(process.cwd(), ".agents/skills/statoz-design-system");
export const claudeSkillDir = path.join(process.cwd(), ".claude/skills/statoz-design-system");

/** The skill's generated reference files, relative to the skill directory. */
export function generatedSkillReferences(sources: DesignSources): Record<string, string> {
  return { "references/tokens.md": renderTokensMarkdown(sources), "references/actions.md": renderActionsMarkdown(), "references/use-cases.md": renderUseCasesMarkdown() };
}

/** A standalone guide for people working outside the studio: foundations, then recipes. */
export function renderDesignGuideMarkdown(sources: DesignSources): string {
  const strip = (markdown: string) => markdown.replace(/^# .*\n\n.*\n\n/, "");
  return ["# StatOz design guide", "The StatOz design system in one file: foundations, actions and elements, use-case recipes, and do/don't. Pair it with statoz-tokens.css and the Orbitron and Onest fonts from the design kit.", strip(renderTokensMarkdown(sources)), "# Actions and elements", strip(renderActionsMarkdown()), "# Use cases", strip(renderUseCasesMarkdown())].join("\n\n");
}
