import { formats, maxPitchPages, type PresentationSlide, type Project, type Scene, type Format, type Sport } from "@/domain/project";
import { appCreativePlaceholders, appShowcaseFormats, standardFormats } from "@/domain/app-creatives";
import { matchStoryPages } from "./match-story-samples";

export type Template = {
  id: string; version: 1; name: string; category: "Product" | "Sports" | "Education" | "Pitch";
  kind: Project["kind"]; description: string; visual: "feature" | "launch" | "card" | "match" | "player" | "stats" | "tutorial" | "grand-prix" | "gameplay" | "match-story" | "news" | "pitch" | "app-showcase" | "play-feature" | "store-icon";
  formats: Format[]; fields: string[]; defaults: Partial<Scene>; hidden?: boolean; maxPages?: number; initialPages?: Partial<Scene>[];
  /** Sport identity this template always carries, for a demo of one specific game. */
  sport?: Sport;
  /** Sport-specific starting pages, used in place of `initialPages`. */
  initialPagesFor?: (sport: Sport) => Partial<Scene>[];
  /** Relative share of a new video's duration for each initial page. */
  durationWeights?: number[];
  /** Format the new-design dialog preselects, when it is not the kind's usual one. */
  defaultFormat?: Format;
};
/** The four beats a gameplay demo opens with: three plays, then the payoff. */
const gameplayPages = (game: string, ...beats: [string, string, string][]): Partial<Scene>[] =>
  beats.map(([eyebrow, headline, body]) => ({ eyebrow, headline, body, showCta: false }))
    .concat([{ eyebrow: "YOUR NEXT MATCH", headline: "Play it\nyourself.", body: `${game} is live in StatOz. Predict. Play. Collect.`, showCta: true }]);
const define = (id: string, name: string, category: Template["category"], kind: Template["kind"], visual: Template["visual"], description: string, defaults: Partial<Scene>): Template =>
  ({ id, version: 1, name, category, kind, visual, description, formats: standardFormats, fields: ["eyebrow", "headline", "body", "cta", "assetId", ...(visual === "match" || visual === "player" || visual === "stats" || visual === "match-story" ? ["nameA", "nameB", "scoreA", "scoreB"] : []), ...(visual === "stats" || visual === "card" || visual === "match" ? ["statLabel", "statValue"] : []), ...(visual === "news" ? ["credit"] : []), ...(visual === "match-story" ? ["beat", "matchStats", "winner", "colorA", "colorB", "emblemA", "emblemB", "graph", "seriesA", "seriesB", "markers", "pickShare", "pickVotes"] : [])], defaults });

export const templates: Template[] = [
  define("feature-spotlight", "Feature spotlight", "Product", "image", "feature", "One feature. One unmistakable statement.", { eyebrow: "THE GAME BEYOND THE GAME", headline: "Your instincts.\nYour arena.", body: "Predict. Play. Collect. Find your next challenge on StatOz.", cta: "Explore StatOz", assetId: "stadium" }),
  define("game-launch", "Game launch", "Product", "image", "launch", "A bold introduction to your next campaign.", { eyebrow: "ENTER THE ARENA", headline: "Every play\nstarts with you.", body: "Meet Pitch Duel. Build your deck. Make your move.", cta: "Discover Pitch Duel", assetId: "", game: "pitch-duel" }),
  define("reward-card", "Rewards & cards", "Product", "image", "card", "Give a collectible its own spotlight.", { eyebrow: "THE COLLECTION", headline: "Built for\nyour next play.", body: "Discover player and action cards in StatOz.", statValue: "92", statLabel: "EXAMPLE RATING", nameA: "THE PLAYMAKER", cta: "Explore the collection" }),
  define("match-preview", "Match preview", "Sports", "image", "match", "Set the stage for the next big fixture.", { eyebrow: "MATCHDAY / PREVIEW", headline: "Two sides.\nOne statement.", body: "Who takes the moment? Make your prediction.", nameA: "NORTH FC", nameB: "SOUTH FC", scoreA: "—", scoreB: "—", statLabel: "EXAMPLE POSSESSION %", statValue: "52 — 48", chartValues: [52, 48], cta: "Join the conversation" }),
  define("match-result", "Match result", "Sports", "image", "match", "The score, the story, the final word.", { eyebrow: "FULL TIME / EXAMPLE", headline: "A finish\nto remember.", body: "The final whistle. A new story to tell.", nameA: "NORTH FC", nameB: "SOUTH FC", scoreA: "3", scoreB: "2", statLabel: "EXAMPLE POSSESSION %", statValue: "52 — 48", chartValues: [52, 48], cta: "What was your moment?" }),
  define("player-spotlight", "Player comparison", "Sports", "image", "player", "Put two performances side by side.", { eyebrow: "HEAD TO HEAD", headline: "Let the\nnumbers talk.", body: "Two standouts. Two different ways to change a game.", nameA: "PLAYER A", nameB: "PLAYER B", scoreA: "28", scoreB: "24", statLabel: "EXAMPLE POINTS", cta: "Who is your pick?" }),
  define("stat-breakdown", "Stat breakdown", "Sports", "image", "stats", "Turn a number into a compelling story.", { eyebrow: "INSIDE THE NUMBERS", headline: "The edge is\nin the details.", body: "A closer look at the numbers behind the performance.", statValue: "78", statLabel: "EXAMPLE ACCURACY %", scoreA: "78", scoreB: "54", cta: "See the bigger picture" }),
  define("explainer", "Swipe-through explainer", "Education", "carousel", "tutorial", "A cover, a clear story, and a strong finish.", { eyebrow: "THE STATOZ PLAYBOOK", headline: "Get closer\nto the game.", body: "Your quick guide to predicting, playing, and collecting.", cta: "Swipe to explore" }),
  define("feature-promo", "Feature promo", "Product", "video", "feature", "Hook, reveal, payoff, and a clear call to action.", { eyebrow: "WELCOME TO STATOZ", headline: "More than\na spectator.", body: "Put your sports instincts into play.", cta: "Discover StatOz", assetId: "stadium" }),
  { ...define("grand-prix-demo", "Grand Prix gameplay demo", "Product", "video", "grand-prix", "A direct-to-canvas demonstration of Grand Prix Dash gameplay, from launch to finish.", { eyebrow: "GRAND PRIX DASH", headline: "Race the\nwhole grid.", body: "Launch clean. Find the tow. Make the pass.", cta: "Play Grand Prix Dash", motion: "none", transition: "cut" }), sport: "motorsport" },
  { ...define("penalty-shootout-demo", "Penalty Shootout gameplay demo", "Product", "video", "gameplay", "A direct-to-canvas demonstration of Penalty Shootout, from the first corner picked to the winning save.", { eyebrow: "PENALTY SHOOTOUT", headline: "Pick your\ncorner.", body: "Aim it. Strike it. Then go and save theirs.", cta: "Play Penalty Shootout", game: "penalty-shootout", motion: "none", transition: "cut" }), sport: "football", initialPages: gameplayPages("Penalty Shootout", ["01 / THE RUN-UP", "Aim it,\nthen strike.", "Sweep the target across the goal and hold the power bar."], ["02 / THE STRIKE", "Find the\ntop corner.", "The keeper commits early. Put it where the gloves cannot reach."], ["03 / YOUR TURN", "Now keep\nit out.", "Read the run-up, choose your side and dive."]) },
  { ...define("final-over-demo", "Final Over gameplay demo", "Product", "video", "gameplay", "A direct-to-canvas demonstration of Final Over, from the run-up to the winning six.", { eyebrow: "FINAL OVER", headline: "Twelve runs.\nFour balls.", body: "Watch the run-up. Time the swing. Clear the ropes.", cta: "Play Final Over", game: "final-over", motion: "none", transition: "cut" }), sport: "cricket", initialPages: gameplayPages("Final Over", ["01 / THE RUN-UP", "The last\nover.", "The chase comes down to four balls and twelve runs."], ["02 / THE TIMING", "Time the\nswing.", "The timing bar decides the shot. Hold it for the middle."], ["03 / THE SHOT", "Clear the\nropes.", "Middled off the front foot. Six runs, and the chase is done."]) },
  { ...define("hoop-duel-demo", "Hoop Duel gameplay demo", "Product", "video", "gameplay", "A direct-to-canvas demonstration of Hoop Duel, from the first crossover to the final buzzer.", { eyebrow: "HOOP DUEL", headline: "Take them\none on one.", body: "Shake the defender. Rise. Release in the green.", cta: "Play Hoop Duel", game: "hoop-duel", motion: "none", transition: "cut" }), sport: "basketball", initialPages: gameplayPages("Hoop Duel", ["01 / THE HANDLE", "Shake the\ndefender.", "Work the crossover until the lane opens up."], ["02 / THE RISE", "Release in\nthe green.", "Rise over the contest and let the meter find its window."], ["03 / THE SHOT", "Nothing\nbut net.", "A pure release. Three points, and the run is on."]) },
  { ...define("tennis-rally-demo", "Tennis Rally gameplay demo", "Product", "video", "gameplay", "A direct-to-canvas demonstration of Tennis Rally, from the first serve to the set.", { eyebrow: "TENNIS RALLY", headline: "Win the\nlong point.", body: "Serve it deep. Hold the rally. Take it down the line.", cta: "Play Tennis Rally", game: "tennis-rally", motion: "none", transition: "cut" }), sport: "tennis", initialPages: gameplayPages("Tennis Rally", ["01 / THE SERVE", "Start with\na big one.", "Place the serve deep and step straight into the point."], ["02 / THE RALLY", "Hold the\nbaseline.", "Slice or drive. Every exchange moves them further across."], ["03 / THE WINNER", "Take it down\nthe line.", "The court opens up. One shot ends the point."]) },
  define("gameplay-tutorial", "Gameplay tutorial", "Education", "video", "tutorial", "Make the first move easy to understand.", { eyebrow: "PITCH DUEL / QUICK START", headline: "Make your\nfirst move.", body: "A quick introduction to your next game.", cta: "Explore Pitch Duel" }),
  { ...define("match-story", "Match & stat story", "Sports", "video", "match-story", "Score, five key stats, the match's flow, then pick your side.", { eyebrow: "THE MATCH IN NUMBERS", headline: "Every number\nhas a story.", body: "Look beyond the scoreline.", statValue: "78", statLabel: "EXAMPLE ACCURACY %", cta: "Pick your side in StatOz", motion: "none" }), initialPagesFor: matchStoryPages, durationWeights: [2, 3, 3, 2] },
  // Example copy only: the default story is invented, so it never reads as reported news.
  { ...define("news-flash", "News flash", "Sports", "image", "news", "A reported headline over its photo, credited and composed for reels and the feed.", { eyebrow: "BREAKING", headline: "North FC *clinch*\nthe title", body: "Example story. Pick a reported ESPN story, or write your own and credit its photo.", cta: "Make your call in StatOz", showCta: false, assetId: "stadium", credit: "PHOTO: STATOZ SAMPLE ARTWORK", cropY: 40 }), defaultFormat: "reel" },
  define("reward-reveal", "Card reveal", "Product", "video", "card", "A cinematic moment for your collection.", { eyebrow: "A NEW ADDITION", headline: "Meet your\nnext playmaker.", body: "Bring a new dimension to your StatOz deck.", statValue: "92", statLabel: "EXAMPLE RATING", nameA: "THE PLAYMAKER", cta: "Explore the collection" }),
  { id: "app-showcase", version: 1, name: "App showcase", category: "Product", kind: "carousel", visual: "app-showcase", description: "One product story, composed for Instagram and exact phone and tablet store placements.", formats: appShowcaseFormats, fields: ["eyebrow", "headline", "body", "cta", "assetId", "tabletAssetId"], defaults: { ...appCreativePlaceholders, cta: "", showCta: false, crop: "contain", assetId: "", tabletAssetId: "" }, maxPages: 8, initialPages: [{}] },
  { id: "play-feature-graphic", version: 1, name: "Google Play feature graphic", category: "Product", kind: "image", visual: "play-feature", description: "A focused 1024 × 500 store-listing hero with restrained StatOz branding.", formats: ["playFeatureGraphic"], fields: ["eyebrow", "headline", "body", "assetId"], defaults: { ...appCreativePlaceholders, eyebrow: "STATOZ / PLAY", cta: "", showCta: false, crop: "contain", assetId: "" }, initialPages: [{}] },
  { id: "store-icon", version: 1, name: "Store icon master", category: "Product", kind: "image", visual: "store-icon", description: "Validate and export one opaque square master for Google Play and Apple delivery.", formats: ["playIcon", "appStoreIcon"], fields: ["assetId"], defaults: { eyebrow: "", headline: "", body: "", cta: "", showLogo: false, showCta: false, crop: "cover", assetId: "statoz-logo" }, initialPages: [{}] },
  { id: "investor-pitch", version: 1, name: "StatOz investor pitch", category: "Pitch", kind: "carousel", visual: "pitch", description: "A twelve-slide starting narrative with room for up to twenty investor slides, grounded in the StatOz product prototype.", formats: ["landscape"], fields: ["eyebrow", "headline", "body", "presentation"], defaults: {}, hidden: true, maxPages: maxPitchPages },
];
export const studioTemplates = templates.filter(template => !template.hidden);
export function templateFor(id: string) {
  const value = templates.find(t => t.id === id);
  if (!value) throw new Error(`Unknown template: ${id}`);
  return value;
}
export function makeScene(overrides: Partial<Scene> = {}): Scene {
  return { id: crypto.randomUUID(), eyebrow: "STATOZ STUDIO", headline: "Your next\nbig moment.", body: "A fresh perspective on the sports you love.", cta: "Explore StatOz", nameA: "NORTH FC", nameB: "SOUTH FC", scoreA: "3", scoreB: "2", statLabel: "EXAMPLE STAT", statValue: "78", chartValues: [37, 59, 48, 72, 61, 78, 54, 91, 74, 96], cardMetrics: { pace: 94, skill: 91, form: 89 }, playerCard: null, presentation: null, assetId: "", tabletAssetId: "", emblemA: "", emblemB: "", game: "", beat: "", matchStats: [], winner: "", colorA: "", colorB: "", graph: "auto", seriesA: [], seriesB: [], markers: [], pickShare: null, pickVotes: "", credit: "", crop: "cover", cropX: 50, cropY: 50, clipStart: 0, clipEnd: 0, duration: 3, layout: "editorial", motion: "rise", transition: "fade", showLogo: true, showCta: true, ...overrides };
}

const productSource = "Product evidence: statoz_web revision 1b9a47a. Product mockups use illustrative data.";
const trendingGamesSource = "Product screen: card_game Games > Trending screenshot-catalog render at 393 x 852. Game data are illustrative.";
const deckSource = "Source: StatOz Investor Pitch Deck (Jan 2026). Claims retain the source deck's stated qualifiers.";
const marketSource = "Source: StatOz Investor Pitch Deck (Jan 2026), citing Naavik / MIXI, India's State of Play (Jul 2026), and YourStory.";
function pitchSlide(headline: string, body: string, presentation: PresentationSlide, eyebrow = "STATOZ / INVESTOR DECK"): Scene {
  return makeScene({ eyebrow, headline, body, cta: "", showCta: false, motion: "none", transition: "cut", presentation });
}
function pitchScenes(): Scene[] {
  return [
    pitchSlide("A live-service\nsports game.", "Real-world sport drives the content. Game systems drive progress and return.", { layout: "cover", visual: "none", bullets: [], metrics: [], evidenceStatus: "source-backed", sourceNote: deckSource }, "STATOZ / SEED ROUND"),
    pitchSlide("India's next wave\nof sports gaming", "A large audience. Growing spend. Room for sports games built around progress.", { layout: "statement", visual: "none", bullets: ["FREE-TO-PLAY / In-app purchases and advertising; excludes real-money gaming"], metrics: [{ value: "600M", label: "ACTIVE GAMERS", detail: "India, 2025 estimate" }, { value: "$1.5B", label: "MOBILE GAME REVENUE", detail: "2026 forecast" }, { value: "$2.4B", label: "MOBILE GAME REVENUE", detail: "2029 forecast" }], evidenceStatus: "source-backed", sourceNote: marketSource }, "WHY NOW"),
    pitchSlide("One sports universe.\nMultiple daily loops.", "Quick sessions feed persistent progress. Players earn coins, collect cards, build decks and return for the next challenge.", { layout: "device", visual: "trending-games", bullets: ["OPEN / Find a fixture", "PLAY / Choose a mode", "EARN / Coins + XP", "BUILD / Cards + decks", "RANK / Compete", "RETURN / Next challenge"], metrics: [], evidenceStatus: "repo-backed", sourceNote: trendingGamesSource }, "THE PRODUCT"),
    pitchSlide("One free-to-play system\nacross sports", "StatOz turns every sports interaction into lasting player progress, without real-money wagering.", { layout: "convergence", visual: "none", bullets: ["SCORES + STATS / Follow the game", "REAL-MONEY PLAY / Stake on outcomes", "QUIZ APPS / Test sports knowledge", "STATOZ / Free-to-play sports gaming", "PROGRESSION / XP, coins, cards and ranks"], metrics: [], evidenceStatus: "illustrative", sourceNote: "Category framing is illustrative and qualitative. StatOz does not offer real-money wagering, deposits or cash-out." }, "DIFFERENT BY DESIGN"),
    pitchSlide("Three systems.\nFive sports.", "Shared progression and content keep the platform connected.", { layout: "device", visual: "game-library", bullets: ["CARD BATTLERS / Deck building, rarity and upgrades", "ARCADE SPORTS / Timing, skill and mastery", "DAILY PUZZLES / Quizzes, streaks and short challenges"], metrics: [{ value: "5", label: "SPORTS", detail: "Cricket, football, basketball, Formula 1, tennis" }], evidenceStatus: "repo-backed", sourceNote: productSource }, "PRODUCT DEPTH"),
    pitchSlide("Every session\ncompounds progress", "Play is the start of a longer journey. Retention mechanisms are built; cohort performance is still to be validated.", { layout: "device", visual: "leaderboard", bullets: ["PLAY / Fast sports sessions", "PROGRESSION / XP tracks + levels", "COLLECTION / Cards + packs", "ECONOMY / Coins + rewards", "COMPETITION / Ranks + milestones", "RETURN / Fixtures + streaks"], metrics: [], evidenceStatus: "repo-backed", sourceNote: "Product evidence: statoz_web revision 1b9a47a. Shop and account data are illustrative; cohort performance is unvalidated." }, "RETENTION"),
    pitchSlide("There is no off-season", "Overlapping sports create match days and tournament moments across the year.", { layout: "seasonality", visual: "none", bullets: [], metrics: [], evidenceStatus: "source-backed", sourceNote: deckSource }, "LIVE OPS"),
    pitchSlide("A free-to-play\nmonetisation stack", "The coin economy exists. The round funds commercial integration. No real-money wagering, deposits or cash-out.", { layout: "device", visual: "storefront", bullets: ["REWARDED VIDEO / Extra hints, retries and lifelines", "COIN PACKS / Top-ups for entries, packs and upgrades", "SEASON PASS / Tournament reward tracks", "COSMETICS / Avatars, frames, kits and card backs"], metrics: [], evidenceStatus: "proposed", sourceNote: "Source: StatOz Investor Pitch Deck (Jan 2026). Existing: local economy, shop and cosmetics. Planned: payments, ads and passes." }, "MONETISATION"),
    pitchSlide("The core game stack exists", "Capital moves the product toward distribution, monetisation and live operations.", { layout: "device", visual: "pitch-duel", bullets: ["META SYSTEMS / Progression, cards, economy, streaks", "GAME FEEL / Motion, audio, haptics, reward reveals", "NEXT INTEGRATIONS / Accounts, commerce and social services"], metrics: [{ value: "18", label: "PLAYABLE GAMES", detail: "Across five sports, plus prediction and pick experiences" }, { value: "5", label: "SPORTS", detail: "Current product coverage" }], evidenceStatus: "repo-backed", sourceNote: productSource }, "WHERE WE ARE"),
    pitchSlide("Built as a game\nfrom day one", "The map separates the player experience from the monetisation model. StatOz targets free-to-play with persistent progression.", { layout: "comparison", visual: "none", bullets: ["UTILITY / Scores + news; consume information", "SESSION PLAY / Casual sports quizzes; play, then reset", "CASH-LINKED CONTESTS / Fantasy or RMG; enter and settle contests", "TARGET QUADRANT / StatOz; build progress over time"], metrics: [], evidenceStatus: "illustrative", sourceNote: "Source: StatOz Investor Pitch Deck (Jan 2026). Category positioning is illustrative and qualitative, not measured market data." }, "POSITIONING"),
    pitchSlide("Prove repeatable growth\nand monetisation", "A focused sequence from foundations to scale readiness. Quarters are measured from funding; milestones are proposed outcomes.", { layout: "timeline", visual: "none", bullets: ["Q1 / Retention foundation: live data, accounts, store relaunch, cohort tracking", "Q2 / Monetisation live: coin store, rewarded video, first tournament pass", "Q3 / Social growth loop: friend challenges, referrals, live-ops tools", "Q4 / Scale readiness: new sports, sponsorships, Series A preparation"], metrics: [], evidenceStatus: "proposed", sourceNote: "Source: StatOz Investor Pitch Deck (Jan 2026). Proposed 12-month roadmap; not a delivery commitment." }, "12-MONTH PLAN"),
    pitchSlide("Sport creates the moments.\nStatOz turns them into a game.", "Raising up to ₹1 Cr in seed equity to fund a 12-month runway for distribution and live operations.", { layout: "closing", visual: "none", bullets: [], metrics: [{ value: "₹1 Cr", label: "SEED EQUITY", detail: "Raising up to" }, { value: "12", label: "MONTH RUNWAY", detail: "Target runway" }, { value: "01", label: "PRIMARY USE", detail: "Distribution + live ops" }], evidenceStatus: "proposed", sourceNote: "Source: StatOz Investor Pitch Deck (Jan 2026). Proposed financing target and use of funds; founder confirmation required." }, "THE ASK"),
  ];
}
export function createProject(templateId: string, format: Format, requestedSport: Sport = "football", duration?: number): Project {
  const template = templateFor(templateId);
  // A demo of one specific game always carries that game's own sport identity.
  const sport = template.sport ?? requestedSport;
  if (!template.formats.includes(format)) throw new Error(`${template.name} does not support ${formats[format].label}.`);
  if (template.kind === "video" && (!duration || duration < 8 || duration > 60)) throw new Error("Choose a video duration from 8 through 60 seconds.");
  const first = makeScene(template.defaults);
  const initialPages = template.initialPagesFor?.(sport) ?? template.initialPages;
  const pages = template.visual === "pitch" ? pitchScenes() : initialPages ? initialPages.map(page => makeScene({ ...template.defaults, ...page })) : template.kind === "image" ? [first] : [first,
    makeScene({ ...template.defaults, eyebrow: template.category === "Sports" ? "01 / THE PERFORMANCE" : "01 / DISCOVER", headline: template.visual === "tutorial" ? "Build\nyour deck." : "A closer\nlook.", body: "Explore the details. Find the moment that matters.", showCta: false }),
    makeScene({ ...template.defaults, eyebrow: template.category === "Sports" ? "02 / THE TAKEAWAY" : "02 / MAKE IT YOURS", headline: template.visual === "tutorial" ? "Make\nyour move." : "Find\nyour edge.", body: "Your perspective brings the story to life.", showCta: false }),
    makeScene({ ...template.defaults, eyebrow: "YOUR NEXT CHAPTER", headline: "See you\nin StatOz.", body: "Predict. Play. Collect.", cta: "Explore StatOz" })];
  if (template.kind === "video") {
    const totalFrames = Math.round(duration! * 30);
    const weights = template.durationWeights?.length === pages.length ? template.durationWeights : undefined;
    if (weights) {
      // Weighted beats round to whole frames; the last scene takes the remainder so the total stays exact.
      const sum = weights.reduce((n, w) => n + w, 0); let assigned = 0;
      pages.forEach((p, i) => { const frames = i === pages.length - 1 ? totalFrames - assigned : Math.round(totalFrames * weights[i] / sum); assigned += frames; p.duration = frames / 30; });
    } else pages.forEach((p, i) => { p.duration = (Math.floor(totalFrames / pages.length) + (i < totalFrames % pages.length ? 1 : 0)) / 30; });
  }
  const now = new Date().toISOString(), projectId = crypto.randomUUID();
  return { schemaVersion: 1, id: projectId, revision: 1, name: template.name, templateId, templateVersion: 1, kind: template.kind, sport, format, outputVariants: [format], pages, pitchDeck: template.visual === "pitch" ? { familyId: projectId, role: "master", variantName: "Master", basedOnProjectId: null, basedOnRevision: null } : null, audio: { assetId: "", gain: .7, silent: template.visual === "pitch", sfx: template.visual !== "pitch" }, brief: { objective: template.description, audience: template.visual === "pitch" ? "Pre-seed and seed investors" : "Sports fans and StatOz players" }, sample: true, archived: false, createdAt: now, updatedAt: now };
}
